["gcp_service_account"] 
type = "service_account"
project_id = "register2025"
private_key_id = "76e94c463ea4f00fc788bbb2775087d82b664905"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDNGREl30aZnfYp
9N6mx7l7mPsPzhtwKvFc8tjITht5dcnBfdFJ2/U++MrGmnA7/3SeazE7uZaakBXj
eHCWwZsOtO7h5/sXwF9CQGGQ67eMHMw4vA9F1h98EOfsaKhPUKClbOiRf6cY4wpL
OMJlADqobdW4LBV3duhjAdgEUpnC3Xfm3dAcxTjbvNZbKmTSZp5RjhoEBHu0I71J
uk4YJen2bvvwXZbCFnq0ATyjuoZpAbfJeY/Cn4p7eyYVSojCp0pUiADaOwqgcYPN
QK8RVv4XcYNwbAvQzrFjSWIOWq3Nuh3f0FYBqmTci8RhPVncSVENj7LAhpopNHHS
y9qObot/AgMBAAECggEADBhzW3Fsf3jCYL0ROHLE7JYcEFWOZrIRo/KqeD2q/yHE
MUYTRrDTKNCRXN8UyWUKYqFduPD8AceHku+ybCGk3FwtTmNY+pCczZJwbpSIMZot
LRdiKzMyjiWNF/MgIfVWVAs1OAd4Ok6Bd+g0BrLZwr8fgIoRBgecMuKT88VPTh+Y
gINGqEm25yRY2XAJr/FiNB6Kzfqxq4pnshsPTxxIYt7hKk0j+Fx//TCqhKPTtHTO
A+YDk2UDykN+V5e8+9AMQcemlCWmofuatso5NoyqCA7yGassipeu2ENLckvLv3V4
gT+Wx4PCaRJvVq8DFRzCZDo+jHHc6eAX5vuFYjxNqQKBgQDmyxwJlHW6IqKO59Q5
CcyH2SB+RjobXf70tLtaiYAnzq2onjykNbFVskuHb0bt9KG74x3F8HHga17ebsKQ
z7B/IrtGHxsTYKa8juCFVLzxQ/ndjcjPXcU+ZGUdQ48U8y20ysleQK84R6vNHDsO
f6/3+i5iaH0TbbH11xVqMuDcNQKBgQDjf4WwTmVoA4jkk0UB/YTy71ZuVeZ7vg/n
WQC2WCmqoa1R6vrYFlUXpcw/SRgZ/gtvsvU5d4d3o6oMwvDY6hYeVNgqFg0JfPpa
/SNK3pazKWBSli8LlUQJ4jPWNMGGwSpzXgMwxpNSacQNtyz3KxC8sdblhtaiPM0D
j+tnKsI3YwKBgQDD0Eg1iJRqHMC3ZtKUok+6YupCuOrMFXAfxse/BTKKk7ybd8YT
vMp83w1eF3eipRAkDYpRSrQTqIWRS4AgxVYGSD2EPRgH1NUi3kZ4WXEFcpso8wcR
iYm0ahGwRoW7TKfW4McBBPilU4ncOLuSjZuLVeTM8cJNHaED6DzvIcPOkQKBgQCf
kYKj91kJa/FI4kM08i2eeGGXYokXomhlTPhC7fPLyztWigsIJiHpRFHO0eYl1RsQ
beWzOTO7pwBPkyx7+TUqcThtzKm4TgEMcSGgEiCB6jO1ucGlzjy68f6J8NcNPdAY
u4hhXedXlvf85s6TT5GdyN+CfuFtSlhCd2AWLNetIQKBgGJdx+U1SxVPlwhpG6x2
Qfux2e0g9wUR4M40IFYD8mhcRviq7v37UVwNim7VtboGxSp7WrEXlUKlfeluouov
CZ8rrmdPN4oiS4WClbHUyOeD4ZZki8JuUd17ZeGTTVrcVgJrJ7+4BV69LfZF0Rfx
Ghtjj7qaRrCA0gdrH9A25bij
-----END PRIVATE KEY-----"""
client_email = "ewe-dataset@register2025.iam.gserviceaccount.com"
client_id = "100454319624432268868"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ewe-dataset%40register2025.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
